version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '07:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore | '
    reviewers:
      - 'marathe-atharva'
    labels:
      - 'dependencies'
